osx: linux
dist: bionic
language: node_js
node_js:
  - '11'
script:
  - npm install
  - npm i -g electron-builder
  - npm rebuild node-sass --force
  - npm run build
  - cd build
  - ls
  - mv Aeneas\ Sanctum\ *.AppImage ../Aeneas.AppImage
  - ls
  - cd ..
  - ls
before_deploy:
  - ls
deploy:
  provider: releases
  api_key:
    secure: BhSs3K78Z7p2R4gYd1wfQiBCF6esUTa2Ug8cmZQ8soFtAyWMIApFbS9er2pKC80bTbJ9thteb0dSVLT5F6gKD/amQt/YP8GbgE24cs2e7sPk24f58oqqcyP5JnRDaAKykqDQKd86zHWR6ko7ATBNICAD0jJxsULV24+8BcUDkgs/1so3nFT8kvSDeFFOFaDkPoha3j5ER6bRGAqcJTA8PiDxXRVP49oLBm+QrKHITKG1VDU/HqzVj6qg79K/pOwPoPHH8CyEGG+ojdmGzSrWCEVjsA7HanRl8HM46TdAccs7AtipzDdLSx6zFdgTe8jnRt6reue8MzAR+PGA3dhuws71GRI48XF4h+j0CTxkpqqlx4353n9vDsIQcrm2Vo/APPLa1VqYf0wfBnVQAYce2pFclLiD/Q3B1gYHVUol9289rwCgwVYC5/492+1FPrnwUYmdWrWBBsaAmMfI1QqE10RLRsTKIPpqprj/NUjo+nB2uhbBZb6pFdNZnQ7gGdR1V2suuP2gaxw2sxQ4jTORArn5XUfsgyNsARw0RQ/AjZ/fVqLlaYa++Z6KGXSD9lMCkofSz4K73ZF3SJPFHUwk6bLhawBc3dhohBo73QB72PB83mxzObG1NMcK8J+avgUvm//JpmQj7Kkzvz+wavcCLSYDedjwQOjEhOjAF5GP7zI=
  file_glob: true
  file:
    - "Aeneas"
  on:
    tags: true
    repo: Aeneas/AeneasElectronClient
    branches:
      only:
        - build-linux